on: [push, pull_request]
name: build
jobs:
  build:
    strategy:
      matrix:
        go: ['1.17', '1.16', '1.15']
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go fmt ./tuf-notary
      - name: Test
        run: go test ./tuf-notary
