name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        go: ['1.17', '1.16', '1.15']
    runs-on: ubuntu-latest
    steps:
      - - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go fmt ./tuf-notary
      - name: Test
        run: go test ./tuf-notary
